name: new_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_linkify: ^6.0.0
  google_fonts: ^6.2.1
  http: ^1.2.2
  link_text: ^0.2.1
  loading_animation_widget: ^1.3.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

